language: node_js
node_js:
  - "10"
  - node

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Run Tests
      node_js: node
      script: ./node_modules/.bin/jest
    # - stage: Produce Coverage
    #   node_js: node
    #   script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
